### ISSUE TITLE
ManyToManyRel.is_hidden() is removed in Django 5.1, causing error in sortedm2m

### ISSUE THREAD

**Issue by philgyford** [jazzband/django-sortedm2m#214]
In the `SortedManyToManyField()` there's a reference ([line 235](https://github.com/jazzband/django-sortedm2m/blob/master/sortedm2m/fields.py#L235)) to `rel.is_hidden()`.

`rel` is a `ManyToManyRel` object.

But a recent commit on Django (https://github.com/django/django/commit/f65f8ab84ebd2fc9772d23a159e6178e1335bd8b) removed the `is_hidden()` method from that class, leaving the `hidden` property instead. Part of [ticket #28011](https://code.djangoproject.com/ticket/28011).

This results in a fatal error when using the latest version of `main` Django and sortedm2m.

[Traceback from a project of mine.](https://github.com/philgyford/django-ditto/actions/runs/8601317394/job/23568296891#step:7:606) Sorry I don't have time right now to create a minimal example.

```
Traceback (most recent call last):
  File "/home/runner/work/django-ditto/django-ditto/.tox/py311-djangomain/bin/django-admin", line 8, in <module>
    sys.exit(execute_from_command_line())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/django-ditto/django-ditto/.tox/py311-djangomain/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/runner/work/django-ditto/django-ditto/.tox/py311-djangomain/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/home/runner/work/django-ditto/django-ditto/.tox/py311-djangomain/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/runner/work/django-ditto/django-ditto/.tox/py311-djangomain/lib/python3.11/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/home/runner/work/django-ditto/django-ditto/.tox/py311-djangomain/lib/python3.11/site-packages/django/apps/config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/work/django-ditto/django-ditto/ditto/flickr/models.py", line 748, in <module>
    class Photoset(TimeStampedModelMixin, DiffModelMixin, models.Model):
  File "/home/runner/work/django-ditto/django-ditto/.tox/py311-djangomain/lib/python3.11/site-packages/django/db/models/base.py", line 194, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/home/runner/work/django-ditto/django-ditto/.tox/py311-djangomain/lib/python3.11/site-packages/django/db/models/base.py", line 371, in add_to_class
    value.contribute_to_class(cls, name)
  File "/home/runner/work/django-ditto/django-ditto/.tox/py311-djangomain/lib/python3.11/site-packages/sortedm2m/fields.py", line 235, in contribute_to_class
    elif rel.is_hidden():
         ^^^^^^^^^^^^^
AttributeError: 'ManyToManyRel' object has no attribute 'is_hidden'. Did you mean: 'hidden'?
```

**Comment by philgyford** [comment]
This is still an issue in the just-released Django 5.1.

**Comment by jet10000** [comment]
django 5.1

```
thon3.12/site-packages/sortedm2m/fields.py", line 235, in contribute_to_class
    elif rel.is_hidden():
         ^^^^^^^^^^^^^
AttributeError: 'ManyToManyRel' object has no attribute 'is_hidden'. Did you mean: 'hidden'?

```

**Comment by neurolabs** [comment]
Thanks @philgyford for the fix, seeing this due to renovate dependency upgrades. Waiting for a compatible release.

**Comment by niccolomineo** [comment]
I am also waiting on this to be officially released. Thanks to everyone for the effort. 🙏

**Comment by clintonb** [comment]
4.0.0 has been released: https://pypi.org/project/django-sortedm2m/
